FoodTrace/urls.py
from django.contrib import admin
from django.urls import path
from app01.views import enterprise, user, food, device, operation, foodbatch, flowrecord, singlefood, material, esp32

urlpatterns = [
    # 展示溯源信息
    path('trace/info/', singlefood.info),
    path('trace/qrcode/', singlefood.image_qrcode),
    path('trace/security/qrcode/', singlefood.security_code),
    path('esp32/validate/food/', singlefood.validate_food),
    # 后端请求接口
    path('esp32/add/',esp32.add),
    path('esp32/trace/info/',esp32.trace_info),
    path('esp32/single/food/info/',esp32.search_single_food),

    # 登录
    path('login/', user.login),
    path('logout/', user.logout),
    path('image/code/', user.image_code),
    # 测试接口
    path('test/ajax/', user.test_ajax),

    # 企业信息管理
    path('enterprise/list/', enterprise.enterprise_list),
    path('enterprise/add/', enterprise.enterprise_add),
    path('enterprise/delete/', enterprise.enterprise_delete),
    path('enterprise/<int:nid>/edit/', enterprise.enterprise_edit),

    # 用户信息管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/delete/', user.user_delete),
    path('user/<int:nid>/reset/', user.user_reset),
    path('user/<int:nid>/edit/', user.user_edit),

    # 食品信息管理
    path('food/list/', food.list),
    path('food/add/', food.add),
    path('food/delete/', food.delete),
    path('food/<int:nid>/edit/', food.edit),

    # 设备信息管理
    path('device/list/', device.list),
    path('device/add/', device.add),
    path('device/delete/', device.delete),
    path('device/<int:nid>/edit/', device.edit),

    # 操作记录信息管理
    path('operation/list/', operation.list),
    path('operation/add/', operation.add),
    path('operation/delete/', operation.delete),
    path('operation/<int:nid>/edit/', operation.edit),

    # 食品批次信息管理
    path('foodbatch/list/', foodbatch.list),
    path('foodbatch/add/', foodbatch.add),
    path('foodbatch/delete/', foodbatch.delete),
    path('foodbatch/<int:nid>/edit/', foodbatch.edit),

    # 食品周转信息管理
    path('flowrecord/list/', flowrecord.list),
    path('flowrecord/add/', flowrecord.add),
    path('flowrecord/delete/', flowrecord.delete),
    path('flowrecord/<int:nid>/edit/', flowrecord.edit),

    # 单位食品信息管理
    path('singlefood/list/', singlefood.list),
    path('singlefood/add/', singlefood.add),
    path('singlefood/delete/', singlefood.delete),
    path('singlefood/<int:nid>/edit/', singlefood.edit),

    # 原材料信息管理
    path('material/list/', material.list),
    path('material/add/', material.add),
    path('material/delete/', material.delete),
    path('material/<int:nid>/edit/', material.edit),
]

app01/models.py
from django.db import models

# Create your models here.
from django.db import models
import django.utils.timezone as timezone
from django.core.validators import RegexValidator  # 正则表达式的模块


class EnterpriseInfo(models.Model):
    """ 企业表 """
    # 如果自己创建主键，django就不会自动给你创建id字段了
    enterpriseID = models.AutoField(verbose_name='企业ID', primary_key=True)
    name = models.CharField(verbose_name='企业名称', max_length=32)
    enterprise_choices = (
        (0, "生产企业"),
        (1, "经销企业"),
        (2, "零售企业"),
    )
    type = models.SmallIntegerField(verbose_name="企业类别", choices=enterprise_choices)
    organization_code = models.CharField(verbose_name='社会信用代码', max_length=18)
    permission_code = models.CharField(verbose_name="食品生产许可证编号", max_length=16)
    address = models.TextField(verbose_name='企业地址', default='无')
    create_time = models.DateField(verbose_name="成立日期", default=timezone.now)
    notes = models.TextField(verbose_name='备注', default='无')

    def __str__(self):
        return self.name  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值


class FoodInfo(models.Model):
    """ 食品信息表 """
    foodID = models.AutoField(verbose_name='食品ID', primary_key=True)
    enterpriseID = models.ForeignKey(verbose_name="所属企业", to="EnterpriseInfo", to_field="enterpriseID",
                                     on_delete=models.CASCADE)
    name = models.CharField(verbose_name="食品名称", max_length=50)
    weight = models.CharField(verbose_name='净含量', max_length=50, default='0')
    chemical_addition = models.TextField(verbose_name='化学食品添加剂', default='无')
    nutrition_table = models.TextField(verbose_name='营养成分表', default='无')
    create_time = models.DateField(verbose_name="登记日期", default=timezone.now)
    notes = models.TextField(verbose_name='备注', default='无')

    def __str__(self):
        return self.name  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值


class UserInfo(models.Model):
    userID = models.AutoField(verbose_name='用户ID', primary_key=True)
    name = models.CharField(verbose_name='用户名',
                            max_length=20,
                            unique=True,
                            validators=[RegexValidator(r'^(\w)+$', '用户名只能有字母数字下划线组成')])
    # \w表示字母下划线的表达式，+表示匹配(\w)表达式一次或多次
    account_num = models.CharField(verbose_name='账号', max_length=20, unique=True)
    password = models.CharField(verbose_name='密码',
                                max_length=20,
                                validators=[RegexValidator(r'^(?![a-z]+$)(?![A-Z]+$)(?!\d+$).{6,20}$',
                                                           '密码必须包含大写\小写字母、数字、特殊字符至少两种,且长度在6-20')]
                                )  # ?![a-z]+$  表示查找不是单纯以小写字母结束的字符串  . 表示匹配除换行符 \n 之外的任何单字符  .{6,20}表示对 . 匹配6-20次
    user_choices = (
        (0, "超级管理员"),
        (1, "企业级管理员"),
        (2, "终端管理员"),
    )
    type = models.SmallIntegerField(verbose_name="用户类别", choices=user_choices)
    enterpriseID = models.ForeignKey(verbose_name="所属企业", to="EnterpriseInfo", to_field="enterpriseID",
                                     on_delete=models.CASCADE, blank=True, null=True)
    create_time = models.DateField(verbose_name="创建日期", auto_now_add=True)  # 在创建时自动添加当前时间，且不可修改

    def __str__(self):
        return self.name  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值


class DeviceInfo(models.Model):
    """ 设备信息表 """
    deviceID = models.AutoField(verbose_name='设备ID', primary_key=True)
    enterpriseID = models.ForeignKey(verbose_name="所属企业", to="EnterpriseInfo", to_field="enterpriseID",
                                     on_delete=models.CASCADE, null=True)
    userID = models.ForeignKey(verbose_name="负责人", to="UserInfo", to_field="userID", on_delete=models.CASCADE,
                               null=True)
    name = models.CharField(verbose_name="设备名称", max_length=16)
    mac_code = models.CharField(verbose_name="MAC号", max_length=16)
    notes = models.TextField(verbose_name='备注', default='无')

    def __str__(self):
        return self.name  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值


class OperationRecord(models.Model):
    """ 操作记录信息表 """
    operateID = models.AutoField(verbose_name='操作ID', primary_key=True)
    userID = models.ForeignKey(verbose_name="负责人", to="UserInfo", to_field="userID", on_delete=models.CASCADE)
    deviceID = models.ForeignKey(verbose_name="操作设备", to="DeviceInfo", to_field="deviceID", on_delete=models.CASCADE)
    operate_datetime = models.DateTimeField(verbose_name="操作时间", auto_now_add=True)
    notes = models.TextField(verbose_name='操作内容', default='添加周转记录')

    def __str__(self):
        return str(self.operateID)  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值


class FoodbatchInfo(models.Model):
    """ 批次信息表 """
    batchID = models.AutoField(verbose_name='批次号', primary_key=True)
    foodID = models.ForeignKey(verbose_name="关联食品", to="FoodInfo", to_field="foodID", on_delete=models.CASCADE)
    amount = models.CharField(verbose_name='数量', max_length=20, default='0')
    quality = models.TextField(verbose_name='抽检结果', default='无')
    manufactureDate = models.DateField(verbose_name="生产日期", default=timezone.now)
    expireDate = models.DateField(verbose_name="截止日期")

    def __str__(self):
        return str(self.batchID)  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值


class FlowRecord(models.Model):
    """ 食品周转信息表 """
    flowID = models.AutoField(verbose_name='周转ID', primary_key=True)
    foodID = models.ForeignKey(verbose_name="关联食品", to="FoodInfo", to_field="foodID", on_delete=models.CASCADE)
    batchID = models.ForeignKey(verbose_name="生产批次号", to="FoodbatchInfo", to_field="batchID", on_delete=models.CASCADE)
    deviceID = models.ForeignKey(verbose_name="操作设备", to="DeviceInfo", to_field="deviceID", on_delete=models.CASCADE)
    userID = models.ForeignKey(verbose_name="负责人", to="UserInfo", to_field="userID", on_delete=models.CASCADE)
    enterpriseID = models.ForeignKey(verbose_name="目的企业", to="EnterpriseInfo", to_field="enterpriseID",
                                     on_delete=models.CASCADE, null=True)
    record_datetime = models.DateTimeField(verbose_name="记录时间", auto_now_add=True)
    quality = models.TextField(verbose_name='质检结果', default='无')

    def __str__(self):
        return str(self.flowID)  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值


class SingleFoodInfo(models.Model):
    """ 单个食品信息表 """
    traceID = models.AutoField(verbose_name='溯源码', primary_key=True)
    foodID = models.ForeignKey(verbose_name="关联食品", to="FoodInfo", to_field="foodID", on_delete=models.CASCADE)
    batchID = models.ForeignKey(verbose_name="生产批次号", to="FoodbatchInfo", to_field="batchID", on_delete=models.CASCADE)
    status_choices = (
        (0, "未被验证"),
        (1, "已被验证"),
    )
    status = models.SmallIntegerField(verbose_name="防伪状态", choices=status_choices, default=0)

    def __str__(self):
        return str(self.traceID)  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值


class MaterialInfo(models.Model):
    """ 食品原材料表 """
    id = models.AutoField(verbose_name='关联ID', primary_key=True)
    product = models.ForeignKey(verbose_name="产品", to="FoodInfo",
                                to_field="foodID", on_delete=models.CASCADE,
                                related_name="product")  # 定义了两个依赖相同表的外键，需要定义related_name的别名
    product_batch = models.ForeignKey(verbose_name="产品批次号", to="FoodbatchInfo",
                                      to_field="batchID", on_delete=models.CASCADE,
                                      related_name="product_batch")
    material = models.ForeignKey(verbose_name="原材料", to="FoodInfo",
                                 to_field="foodID", on_delete=models.CASCADE,
                                 related_name="material")
    material_batch = models.ForeignKey(verbose_name="原材料批次号", to="FoodbatchInfo",
                                       to_field="batchID", on_delete=models.CASCADE,
                                       related_name="material_batch")

    def __str__(self):
        return str(self.id)  # 在modelform中显示外键为对象的输出函数，这里定义对象print时显示的值

app01/views/device.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import DeviceModelForm

table_title = '设备'
search_info = '设备名'

def list(request):
    """ 显示信息表 """
    # 搜索功能
    data_dict = {}
    info_dict = request.session.get("info")
    if info_dict:
        if info_dict['type_name'] != '超级管理员':
            data_dict["enterpriseID"] = info_dict["enterpriseID"]

    search_data = request.GET.get('q', "")  # 得到搜索框的数据
    if search_data:
        data_dict["name__contains"] = search_data  # __contains表示name字段中包含，类似于LIKE
    # 去数据库中获取所有的元组，如果查询框中有数据，则筛选数据
    queryset = models.DeviceInfo.objects.filter(**data_dict)
    # 自动生成表头名字
    table_head = []
    for item in models.DeviceInfo._meta.fields:
        table_head.append(item.verbose_name)

        # 2.实例化分页对象
    page_object = Pagination(request, queryset)

    context = {
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html(),  # 生成页码
        "search_data": search_data,
        "table_title": table_title,
        "search_info": search_info,
        "table_head": table_head,
        "form": DeviceModelForm(),
    }
    return render(request, 'device_list.html', context)

def add(request):
    """ 添加信息 """
    context = {
        "table_title": table_title,
        "method": "新建",
    }
    if request.method == "GET":
        form = DeviceModelForm()
        context["form"] = form
        return render(request, 'add_edit.html', context)
    # 用户POST提交数据，数据校验。
    form = DeviceModelForm(data=request.POST)
    if form.is_valid():
        # 如果数据合法，保存到数据库
        form.save()
        return redirect('/device/list/') #页面重定向

    # 校验失败（在页面上显示错误信息）
    context["form"] = form
    return render(request, 'add_edit.html', context)


def delete(request):
    """ 删除信息 """
    nid = request.GET.get('nid')
    models.DeviceInfo.objects.filter(deviceID=nid).delete()
    return redirect("/device/list/")


def edit(request, nid):
    """ 修改信息 """
    context = {
        "table_title": table_title,
        "method": "编辑",
    }
    row_object = models.DeviceInfo.objects.filter(deviceID=nid).first()
    if not row_object:
        # 数据不存在的情况，返回原编辑页面
        return redirect('/device/list/')
    if request.method == "GET":
        # 根据ID去数据库获取要编辑的那一行数据（对象）
        form = DeviceModelForm(instance=row_object)
        context["form"] = form
        return render(request, 'add_edit.html', context)

    form = DeviceModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/device/list/')
    context["form"] = form
    return render(request, 'add_edit.html', context)

app01/views/enterprise.py
from django.shortcuts import render, redirect
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import EnterpriseModelForm

table_title = '企业'

def enterprise_list(request):
    """ 显示用户信息表 """
    # 搜索功能
    data_dict = {}
    search_data = request.GET.get('q', "")  # 得到搜索框的数据
    if search_data:
        data_dict["name__contains"] = search_data  # __contains表示name字段中包含，类似于LIKE
    # 去数据库中获取所有的元组，如果查询框中有数据，则筛选数据
    queryset = models.EnterpriseInfo.objects.filter(**data_dict)
    # 自动生成表头名字
    table_head = []
    for item in models.EnterpriseInfo._meta.fields:
        table_head.append(item.verbose_name)

        # 2.实例化分页对象
    page_object = Pagination(request, queryset)

    context = {
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html(),  # 生成页码
        "search_data": search_data,
        "table_title": table_title,
        "table_head": table_head,
        "form": EnterpriseModelForm(),
    }
    return render(request, 'enterprise_list.html', context)

def enterprise_add(request):
    """ 添加用户信息 """
    context = {
        "table_title": table_title,
        "method": "新建",
    }
    if request.method == "GET":
        form = EnterpriseModelForm()
        context["form"] = form
        return render(request, 'add_edit.html', context)
    # 用户POST提交数据，数据校验。
    form = EnterpriseModelForm(data=request.POST)
    if form.is_valid():
        # 如果数据合法，保存到数据库
        form.save()
        return redirect('/enterprise/list/') #页面重定向

    # 校验失败（在页面上显示错误信息）
    context["form"] = form
    return render(request, 'add_edit.html', context)


def enterprise_delete(request):
    """ 删除用户信息 """
    # 获取ID http://127.0.0.1:8000/enterprise/delete/?nid=1
    nid = request.GET.get('nid')
    # 删除
    models.EnterpriseInfo.objects.filter(enterpriseID=nid).delete()
    # 重定向回企业信息列表
    return redirect("/enterprise/list/")


def enterprise_edit(request, nid):
    """ 修改用户信息 """
    context = {
        "table_title": table_title,
        "method": "编辑",
    }
    row_object = models.EnterpriseInfo.objects.filter(enterpriseID=nid).first()
    if not row_object:
        # 数据不存在的情况，返回原编辑页面
        return redirect('/user/list/')
    if request.method == "GET":
        # 根据ID去数据库获取要编辑的那一行数据（对象）
        form = EnterpriseModelForm(instance=row_object)
        context["form"] = form
        return render(request, 'add_edit.html', context)

    form = EnterpriseModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 如果用户提交数据校验成功
        # 默认保存的是用户输入的所有数据，如果想要再用户输入以外增加一点值
        # form.instance.字段名 = 值
        form.save()
        return redirect('/enterprise/list/')
    context["form"] = form
    return render(request, 'add_edit.html', context)

app01/templates/add_edit.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}

    <div class="card mb-4">
        <div class="card-header">
            <h5>{{ method }}{{ table_title }}信息</h5>
        </div>
        <div class="card-body">
            <form method="post" novalidate>{#novalidate是关闭浏览器校验#}
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        {{ field }}
                        <span style="color: red;">{{ field.errors.0 }}</span>
                        {#field.errors.0是拿第0个错误#}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>

{% endblock %}


{% block js %}
<script src="{% static 'plugins/date/jedate/jedate.js' %}"></script>
{% if table_title == "食品批次" %}
<script type="text/javascript">
    jeDate({
        dateCell: "#id_manufactureDate",
        format: "YYYY-MM-DD", //控制是否显示小时
    });
    jeDate({
        dateCell: "#id_expireDate",
        format: "YYYY-MM-DD", //控制是否显示小时
    });
</script>
{% elif table_title == "企业" or table_title == "食品" %}
 <script type="text/javascript">
    jeDate({
        dateCell: "#id_create_time",
        format: "YYYY-MM-DD", //控制是否显示小时
    });
</script>
{% endif %}
{% endblock %}

app01/templates/device_list.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <div class="card mb-4">
        <!-- Default panel contents -->
        <div class="card-header">
            <i class="fas fa-table"></i>
            {{ table_title }}信息表
            <div style="display: inline-block;margin-left: 15px;">
                <a class="btn btn-primary btn-sm" href="/device/add/">
                    <i class="fa-solid fa-plus"></i>
                    新建
                </a>
            </div>
            <div style="width: 270px;position:absolute;top:4px;right:10px;display: inline-block;">
                <form method="get">
                    <div class="input-group mb-3">
                        <input type="text" name="q" class="form-control" placeholder="按{{ search_info }}模糊查询"
                               aria-label="按{{ search_info }}名模糊查询" aria-describedby="按{{ search_info }}模糊查询">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
                            <i class='fas fa-magnifying-glass' style="color: #0f0f0f;"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!-- Table -->
        <div class="card-body">
            <table class="table table-striped table-hover table-sm">
                <thead>
                <tr>
                    {% for item in table_head %}
                        <th>{{ item }}</th>
                    {% endfor %}
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.deviceID }}</td>
                        <td>{{ obj.enterpriseID }}</td>
                        <td>{{ obj.userID }}</td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.mac_code }}</td>
                        <td>{{ obj.notes }}</td>
                        <td>
                            <a class="btn btn-primary btn-sm" href="/device/{{ obj.deviceID }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-sm" href="/device/delete/?nid={{ obj.deviceID }}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}

app01/templates/enterprise_list.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <div class="card mb-4">
        <!-- Default panel contents -->
        <div class="card-header">
            <i class="fas fa-table"></i>
            {{ table_title }}信息表
            <div style="display: inline-block;margin-left: 15px;">
                <a class="btn btn-primary btn-sm" href="/enterprise/add/">
                    <i class="fa-solid fa-plus"></i>
                    新建
                </a>
            </div>
            <div style="width: 270px;position:absolute;top:4px;right:10px;display: inline-block;">
                <form method="get">
                    <div class="input-group mb-3">
                        <input type="text" name="q" class="form-control" placeholder="按{{ table_title }}名模糊查询"
                               aria-label="按{{ table_title }}名模糊查询" aria-describedby="按{{ table_title }}名模糊查询">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
                            <i class='fas fa-magnifying-glass' style="color: #0f0f0f;"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!-- Table -->
        <div class="card-body">
            <table class="table table-striped table-hover table-sm" style="table-layout: fixed;">
                <thead>
                <tr>
                    <th width="50px">企业ID</th>
                    <th width="170px">企业名称</th>
                    <th width="74px">企业类别</th>
                    <th width="150px">社会信用代码</th>
                    <th width="100px">食品生产许可证编号</th>
                    <th width="150px">企业地址</th>
                    <th width="105px">成立日期</th>
                    <th width="50px">备注</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;">{{ obj.enterpriseID }}</td>
                        <td title="{{ obj.name }}"style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;">{{ obj.name }}</td>
                        <td style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;">{{ obj.get_type_display }}</td>
                        <td style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;" title="{{ obj.organization_code }}">{{ obj.organization_code }}</td>
                        <td style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;" title="{{ obj.permission_code }}">{{ obj.permission_code }}</td>
                        <td style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;" title="{{ obj.address }}">{{ obj.address }}</td>
                        <td style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;">{{ obj.create_time|date:"Y-m-d" }}</td>
                        <td style="overflow: hidden;white-space: nowrap;text-overflow: ellipsis;" title="{{ obj.notes }}">{{ obj.notes }}</td>
                        <td>
                            <a class="btn btn-primary btn-sm" href="/enterprise/{{ obj.enterpriseID }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-sm"
                               href="/enterprise/delete/?nid={{ obj.enterpriseID }}">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.name }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <a>
                        <img id="image_code" src="/image/code/" style="width: 125px;">
                    </a>
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>

</body>
</html>

app01/templates/singlefood_list.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <div class="card mb-4">
        <!-- Default panel contents -->
        <div class="card-header">
            <i class="fas fa-table"></i>
            {{ table_title }}信息表
            <div style="display: inline-block;margin-left: 15px;">
                <a class="btn btn-primary btn-sm" href="/singlefood/add/">
                    <i class="fa-solid fa-plus"></i>
                    新建
                </a>
            </div>
            <div style="width: 270px;position:absolute;top:4px;right:10px;display: inline-block;">
                <form method="get">
                    <div class="input-group mb-3">
                        <input type="text" name="q" class="form-control" placeholder="按{{ search_info }}模糊查询"
                               aria-label="按{{ search_info }}名模糊查询" aria-describedby="按{{ search_info }}模糊查询">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
                            <i class='fas fa-magnifying-glass' style="color: #0f0f0f;"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!-- Table -->
        <div class="card-body">
            <table class="table table-striped table-hover table-sm">
                <thead>
                <tr>
                    {% for item in table_head %}
                        <th>{{ item }}</th>
                    {% endfor %}
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.traceID }}</td>
                        <td>{{ obj.foodID }}</td>
                        <td>{{ obj.batchID }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>
                            <a class="btn btn-primary btn-sm" href="/singlefood/{{ obj.traceID }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-sm" href="/singlefood/delete/?nid={{ obj.traceID }}">删除</a>
                            <a class="btn btn-primary btn-sm" href="/trace/info/?nid={{ obj.traceID }}">溯源二维码</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}